# =============================================================================
# Gateway Service Configuration (Centralized in Config Server)
# =============================================================================
# This configuration is loaded by gateway-service from Config Server
# Author: Amsidh Mohammed
# Date: October 31, 2025
# =============================================================================

# Spring Cloud Gateway Configuration
spring:
  cloud:
    gateway:
      # Service Discovery Integration
      discovery:
        locator:
          enabled: true  # Enable automatic route creation from Eureka
          lower-case-service-id: true  # Convert service names to lowercase
      
      # Explicit Route Definitions
      routes:
        # =============================================================================
        # AUTH SERVICE ROUTE - JWT Authentication & Token Management
        # =============================================================================
        - id: auth-service
          uri: lb://AUTH-SERVICE  # Load-balanced via Eureka
          predicates:
            - Path=/api/v1/auth-service/**
          metadata:
            description: "JWT Authentication Service"
        
        # =============================================================================
        # BUSINESS SERVICE ROUTES
        # =============================================================================
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer-service/**
          metadata:
            description: "Customer Management Service"

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product-service/**
          metadata:
            description: "Product Catalog Service"

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-service/**
          metadata:
            description: "Order Processing Service"

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment-service/**
          metadata:
            description: "Payment Processing Service"

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification-service/**
          metadata:
            description: "Notification Service"
      
      # Global CORS Configuration
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: false
            max-age: 3600

# =============================================================================
# Auth Service Configuration (for AuthenticationFilter)
# =============================================================================
auth:
  service:
    url: lb://AUTH-SERVICE  # Load-balanced via Eureka service discovery
    validate-endpoint: /api/v1/auth-service/auth/validate

# =============================================================================
# Management & Actuator Configuration
# =============================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway,httptrace
  endpoint:
    health:
      show-details: always
    gateway:
      access: read_only  # Gateway actuator endpoint access level
  
  # Distributed Tracing Configuration
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for all requests
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  
  # Metrics Configuration
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

# =============================================================================
# Logging Configuration
# =============================================================================
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com.amsidh.mvc: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: INFO

