spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.amsidh.mvc.kafka.order.OrderConfirmation

# Microservice Inter-service Communication Configuration
application:
  config:
    customer-service:
      # This should be customer-service gateway url
      url: http://localhost:8080/api/v1/customer-service/customers
    product-service:
      # This should be product-service gateway url
      url: http://localhost:8080/api/v1/product-service/products
    payment-service:
      # This should be payment-service gateway url
      url: http://localhost:8080/api/v1/payment-service/payments






