server:
  port: 8761

spring:
  application:
    name: discovery-service
  config:
    #import: optional:configserver:http://localhost:8888/config-server/api/v1/config
    import: configserver:http://localhost:8888/config-server/api/v1/config

